Basic Slicing and Advanced Indexing in NumPy :

Indexing Using Index arrays :


Indexing can be done in NumPy by using an array as an index.

Numpy arrays can be indexed with other arrays or any other sequence with the exception of tuples. The last element is indexed by -1 second last by -2 and so on.

In the case of slicing, a view or shallow copy of the array is returned but in an index array, a copy of the original array is returned.

In [2]:
import numpy as np 
# Create a sequence of integers from 10 to 1 with a step of -2 
a = np.arange(10, 1, -2) 
print("\n A sequential array with a negative step: \n",a) 
# Indexes are specified inside the np.array method. 
newarr = a[np.array([3, 1, 2 ])] 
print("\n Elements at these indices are:\n",newarr)



 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


Basic Slicing and indexing :

In [6]:
import numpy as np 
# Arrange elements from 0 to 19 
a = np.arange(20) 
print("\nArray is:\n ",a) 
print("\na[15]=",a[15]) 
# a[start:stop:step] 
print("\na[-8:17:1] = ",a[-8:17:1]) 
print("\na[10:] = ",a[10:])



Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

a[15]= 15

a[-8:17:1] =  [12 13 14 15 16]

a[10:] =  [10 11 12 13 14 15 16 17 18 19]


In [7]:
import numpy as np 
# A 3 dimensional array. 
b = np.array([[[1, 2, 3],[4, 5, 6]], 
			[[7, 8, 9],[10, 11, 12]]]) 
print(b[...,1]) #Equivalent to b[: ,: ,1 ]


[[ 2  5]
 [ 8 11]]


Advanced indexing :

NumPy Advanced indexing returns a copy of data rather than a view of it. Advanced indexing is of two types integer and Boolean.

Types of Advanced Indexing:

There are two types of Advanced Indexing in NumPy array indexing:

* Purely integer indexing
 
* Boolean integer indexing

Purely integer array indexing :

In [8]:
# Python program showing advanced indexing 
import numpy as np 
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]]) 
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])


[1 3 6]


Boolean Indexing :

This indexing has some boolean expressions as the index.

Those elements are returned which satisfy that Boolean expression. It is used for filtering the desired element values.

In [9]:
# You may wish to select numbers greater than 50 
import numpy as np 

a = np.array([10, 40, 80, 50, 100]) 
print(a[a>50])


[ 80 100]


In [10]:
# You may wish to select those elements whose 
# sum of row is a multiple of 10. 
import numpy as np 

b = np.array([[5, 5],[4, 5],[16, 4]]) 
sumrow = b.sum(-1) 
print(b[sumrow%10==0]) 


[[ 5  5]
 [16  4]]


numpy.compress() :

In [11]:
# Python Program illustrating 
# numpy.compress method 

import numpy as geek 

array = geek.arange(10).reshape(5, 2) 
print("Original array : \n", array) 

a = geek.compress([0, 1], array, axis=0) 
print("\nSliced array : \n", a) 

a = geek.compress([False, True], array, axis=0) 
print("\nSliced array : \n", a) 


Original array : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Sliced array : 
 [[2 3]]

Sliced array : 
 [[2 3]]


Accessing Data Along Multiple Dimensions Arrays in Python Numpy :

In [12]:
# 1-dimensional array
array1D = np.array([1, 2, 3, 4, 5])

print(array1D)

# to access elements using positive
# index
print("\nusing positive index :" +str(array1D[0]))
print("using positive index :" +str(array1D[4]))

# negative indexing works in opposite
# direction
print("\nusing negative index :" +str(array1D[-5]))
print("using negative index :" +str(array1D[-1]))


[1 2 3 4 5]

using positive index :1
using positive index :5

using negative index :1
using negative index :5


In [13]:
# 2-dimensional array 
array2D = np.array([[93, 95],
					[84, 100],
					[99, 87]])

print(array2D)
print("shape :" +str(array2D.shape))

print("\npositive indexing :" +str(array2D[1, 0]))
print("negative indexing :" +str(array2D[-2, 0]))

print("\nslicing using positive indices :" +str(array2D[0:3, 1]))
print("slicing using positive indices :" +str(array2D[:, 1]))
print("slicing using negative indices :" +str(array2D[:, -1]))


[[ 93  95]
 [ 84 100]
 [ 99  87]]
shape :(3, 2)

positive indexing :84
negative indexing :84

slicing using positive indices :[ 95 100  87]
slicing using positive indices :[ 95 100  87]
slicing using negative indices :[ 95 100  87]


In [14]:
# 3-dimensional array 
array3D = np.array([[[ 0, 1, 2],
					[ 3, 4, 5],
					[ 6, 7, 8]],

					[[ 9, 10, 11],
					[12, 13, 14],
					[15, 16, 17]],

					[[18, 19, 20],
					[21, 22, 23],
					[24, 25, 26]]])

print(array3D)
print("shape :" +str(array3D.shape))

print("\naccessing element :" +str(array3D[0, 1, 0]))
print("accessing elements of a row and a column of an array:"
	+str(array3D[:, 1, 0]))
print("accessing sub part of an array :" +str(array3D[1]))


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
shape :(3, 3, 3)

accessing element :3
accessing elements of a row and a column of an array:[ 3 12 21]
accessing sub part of an array :[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


access different rows of a multidimensional NumPy array :

In [15]:
# Importing Numpy module 
import numpy as np 

# Creating a 3X3 2-D Numpy array 
arr = np.array([[10, 20, 30], 
				[40, 5, 66], 
				[70, 88, 94]]) 

print("Given Array :") 
print(arr) 

# Access the First and Last rows of array 
res_arr = arr[[0,2]] 
print("\nAccessed Rows :") 
print(res_arr)


Given Array :
[[10 20 30]
 [40  5 66]
 [70 88 94]]

Accessed Rows :
[[10 20 30]
 [70 88 94]]


In [16]:
# Importing Numpy module 
import numpy as np 

# Creating a 3X4 2-D Numpy array 
arr = np.array([[101, 20, 3, 10], 
				[40, 5, 66, 7], 
				[70, 88, 9, 141]]) 
				
print("Given Array :") 
print(arr) 

# Access the Middle row of array 
res_arr = arr[1] 
print("\nAccessed Row :") 
print(res_arr)


Given Array :
[[101  20   3  10]
 [ 40   5  66   7]
 [ 70  88   9 141]]

Accessed Row :
[40  5 66  7]


In [17]:
# Importing Numpy module 
import numpy as np 

# Creating a 4X4 2-D Numpy array 
arr = np.array([[1, 20, 3, 1], 
				[40, 5, 66, 7], 
				[70, 88, 9, 11], 
			[80, 100, 50, 77]]) 

print("Given Array :") 
print(arr) 

# Access the Last three rows of array 
res_arr = arr[[1,2,3]] 
print("\nAccessed Rows :") 
print(res_arr)


Given Array :
[[  1  20   3   1]
 [ 40   5  66   7]
 [ 70  88   9  11]
 [ 80 100  50  77]]

Accessed Rows :
[[ 40   5  66   7]
 [ 70  88   9  11]
 [ 80 100  50  77]]


In [18]:
# Importing Numpy module 
import numpy as np 

# Creating a 5X4 2-D Numpy array 
arr = np.array([[1, 20, 3, 1], 
				[40, 5, 66, 7], 
				[70, 88, 9, 11], 
			[80, 100, 50, 77], 
			[1, 8.5, 7.9, 4.8]]) 

print("Given Array :") 
print(arr) 

# Access the First two rows of array 
res_arr = arr[[0,1]] 
print("\nAccessed Rows :") 
print(res_arr)


Given Array :
[[  1.   20.    3.    1. ]
 [ 40.    5.   66.    7. ]
 [ 70.   88.    9.   11. ]
 [ 80.  100.   50.   77. ]
 [  1.    8.5   7.9   4.8]]

Accessed Rows :
[[ 1. 20.  3.  1.]
 [40.  5. 66.  7.]]
