NUMPY - PYTHON :

What is NumPy? 

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object and tools for working with these arrays. It is the fundamental package for scientific computing with Python. It is open-source software.

--> Arrays in NumPy :

* It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
* In NumPy, dimensions are called axes. The number of axes is rank.
* NumPy array class is called ndarray. It is also known by the alias array.

Example:

In this example, we are creating a two-dimensional array that has the rank of 2 as it has 2 axes. The first axis(dimension) is of length 2, i.e., the number of rows, and the second axis(dimension) is of length 3, i.e., the number of columns. The overall shape of the array can be represented as (2, 3)

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,2,5]]) # Creating array object 

In [4]:
print("array of type:",type(arr)) # Printing type of arr object 
print("no.of.dimensions:",arr.ndim) # Printing array dimensions (axes) 
print("size of array:",arr.size) # Printing size (total number of elements) of array 
print("shape of array:",arr.shape) # Printing shape of array 
print("array stores elements of type:",arr.dtype) # Printing type of elements in array 

array of type: <class 'numpy.ndarray'>
no.of.dimensions: 2
size of array: 6
shape of array: (2, 3)
array stores elements of type: int32


--> NumPy Array Creation :


There are various ways of Numpy array creation in Python. They are as follows:

1. You can create an array from a regular Python list or tuple using the array() function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [11]:
import numpy as np

# Creating array from list with type float 
a = np.array([[1,2,4],[5,8,7]], dtype = 'float')
print("array created using passed list:\n",a)

# Creating array from tuple 
b = np.array((1,3,2))
print("\narray created using passed tuple:\n",b)

array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

array created using passed tuple:
 [1 3 2]


2. Often, the element is of an array is originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

example: np.zeros, np.ones, np.full, np.empty, etc.

To create sequences of numbers, NumPy provides a function analogous to the range that returns arrays instead of lists.

In [13]:
c = np.zeros((3,4))  # Creating a 3X4 array with all zeros 
print("an array initialized with all zeros:\n",c)

d=np.full((3,3),7,dtype = 'complex')  # Create a constant value array of complex type 
print("an array initialized with all 7s."
         "array type is complex:\n",d)

e=np.random.random((2,2)) # Create an array with random values 
print("a random array:\n",e)

an array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
an array initialized with all 7s.array type is complex:
 [[7.+0.j 7.+0.j 7.+0.j]
 [7.+0.j 7.+0.j 7.+0.j]
 [7.+0.j 7.+0.j 7.+0.j]]
a random array:
 [[0.47359092 0.55232334]
 [0.2029348  0.77795023]]


3. arange :
   
 This function returns evenly spaced values within a given interval. 

In [16]:
#create a sequence of integers
#from 0 to 30 with steps of 5
f=np.arange(0,30,6)
print("a sequential array with steps of 6:\n",f)

a sequential array with steps of 6:
 [ 0  6 12 18 24]


4. linspace:

It returns evenly spaced values within a given interval.

In [20]:
# create a sequence of 10 values in range 0 to 5
g = np.linspace(0,6,10)
print("a sequential array with 10 values between"
                         "0 and 6:\n",g)

a sequential array with 10 values between0 and 6:
 [0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]


5. Reshaping array:

 We can use reshape method to reshape an array

In [27]:
arr = np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])

newarr = arr.reshape(2,2,3)  # Reshaping 3X4 array to 2X2X3 array 

print("original array:\n",arr)
print("-------------------")
print("reshape array:\n",newarr)

original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
-------------------
reshape array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


6. Flatten array:

   We can use flatten method to get a copy of the array collapsed into one dimension. 

In [28]:
#flatten array
arr = np.array([[1,2,3],[4,5,6]])
flat_arr = arr.flatten()

print("original array:\n",arr)
print("flatten array:\n",flat_arr)

original array:
 [[1 2 3]
 [4 5 6]]
flatten array:
 [1 2 3 4 5 6]


NumPy Array Indexing :

Slicing: 

Just like lists in Python, NumPy arrays can be sliced. As arrays can be multidimensional, we need to specify a slice for each dimension of the array.

Integer array indexing:

In this method, lists are passed for indexing for each dimension. One-to-one mapping of corresponding elements is done to construct a new arbitrary array.

Boolean array indexing:

This method is used when we want to pick elements from the array which satisfy some condition.

In [36]:
#indexing in numpy
import numpy as np

#an exemplar array
arr = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])

#slicing array
tem = arr[:2, ::2]
print("array with first 2 rows and alternate column (0 and 2):\n", temp)

#integer array indexing example
temp = arr[[0, 1, 2, 3],[3, 2, 1, 0]]
print("\nelements at indices (0,3), (1,2), (2,1), (3,0):\n", temp)

#boolean array indexing example
cond = arr > 0 
temp = arr[cond]
print("\nelements greater than 0:\n", temp)

array with first 2 rows and alternate column (0 and 2):
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]

elements at indices (0,3), (1,2), (2,1), (3,0):
 [4. 6. 0. 3.]

elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


NumPy Basic Operations :

Operations on a single NumPy array : +=, -=, *= operators.

In [38]:
import numpy as np

a = np.array([1, 2, 5, 3])

print("adding 1 to every element:", a+1) # add 1 to every element 

print("subracting 3 from every element:", a-3) # subtract 3 from each element 

print("multiplying 10 by each element:", a*10) # multiply each element by 10 

print("squaring each element:", a**2) # square each element 

# modify existing array 
a *= 2
print("doubled each element of original arra:", a)

a= np.array([[1,2,3],[3,4,5],[9,6,0]]) # transpose of array 

print("original array:", a)
print("transpose array:", a.T)

adding 1 to every element: [2 3 6 4]
subracting 3 from every element: [-2 -1  2  0]
multiplying 10 by each element: [10 20 50 30]
squaring each element: [ 1  4 25  9]
doubled each element of original arra: [ 2  4 10  6]
original array: [[1 2 3]
 [3 4 5]
 [9 6 0]]
transpose array: [[1 3 9]
 [2 4 6]
 [3 5 0]]


NumPy – Unary Operators :

Many unary operations are provided as a method of ndarray class. This includes sum, min, max, etc. These functions can also be applied row-wise or column-wise by setting an axis parameter.

In [39]:
import numpy as np 
  
arr = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]]) 
  
# maximum element of array 
print ("Largest element is:", arr.max()) 
print ("Row-wise maximum elements:", 
                    arr.max(axis = 1)) 
  
# minimum element of array 
print ("Column-wise minimum elements:", 
                        arr.min(axis = 0)) 
  
# sum of array elements 
print ("Sum of all array elements:", 
                            arr.sum()) 
  
# cumulative sum along each row 
print ("Cumulative sum along each row:\n", 
                        arr.cumsum(axis = 1)) 

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


NumPy – Binary Operators :

These operations apply to the array elementwise and a new array is created.The basic arithmetic operators like +, -, /,  etc. In the case of +=, -=, = operators, the existing array is modified.


In [40]:
import numpy as np 
  
a = np.array([[1, 2], 
            [3, 4]]) 
b = np.array([[4, 3], 
            [2, 1]]) 
  
# add arrays 
print ("Array sum:\n", a + b) 
  
# multiply arrays (elementwise multiplication) 
print ("Array multiplication:\n", a*b) 
  
# matrix multiplication 
print ("Matrix multiplication:\n", a.dot(b)) 

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


NymPy’s ufuncs :

NumPy provides familiar mathematical functions such as sin, cos, exp, etc.

All the operations we did above using overloaded operators can be done using ufuncs like np.add, np.subtract, np.multiply, np.divide, np.sum, etc. 

In [43]:
import numpy as np 
  
# create an array of sine values 
a = np.array([0, np.pi/2, np.pi]) 
print ("Sine values of array elements:", np.sin(a)) 
  
# exponential values 
a = np.array([0, 1, 2, 3]) 
print ("Exponent of array elements:", np.exp(a)) 
  
# square root of array values 
print ("Square root of array elements:", np.sqrt(a)) 

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


NumPy Sorting Arrays :

There is a simple np.sort() method for sorting Python NumPy arrays

In [44]:
import numpy as np 
  
a = np.array([[1, 4, 2], 
                 [3, 4, 6], 
              [0, -1, 5]]) 
  
# sorted array 
print ("Array elements in sorted order:\n", 
                    np.sort(a, axis = None)) 
  
# sort array row-wise 
print ("Row-wise sorted array:\n", 
                np.sort(a, axis = 1)) 
  
# specify sort algorithm 
print ("Column wise sort by applying merge-sort:\n", 
            np.sort(a, axis = 0, kind = 'mergesort')) 
  
# Example to show sorting of structured array 
# set alias names for dtypes 
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)] 
  
# Values to be put in array 
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),  
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)] 
# Creating array 
arr = np.array(values, dtype = dtypes) 
print ("\nArray sorted by names:\n", 
            np.sort(arr, order = 'name')) 
              
print ("Array sorted by graduation year and then cgpa:\n", 
                np.sort(arr, order = ['grad_year', 'cgpa'])) 


Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


Creating a Numpy Array :


In [48]:
import numpy as np

arr = np.array([1, 2, 3]) # Creating a rank 1 Array
print("array with rank:",arr)

arr = np.array([[1, 2, 3],[4, 5, 6]]) # Creating a rank 2 Array
print("array with rank2:",arr)

arr = np.array((1, 3, 4)) # Creating an array from tuple
print("array created using passed tuple:", arr)

array with rank: [1 2 3]
array with rank2: [[1 2 3]
 [4 5 6]]
array created using passed tuple: [1 3 4]


Accessing the array Index :

In [49]:
import numpy as np
 
# Initial Array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Initial Array: ")
print(arr)
 
# Printing a range of Array
# with the use of slicing method
sliced_arr = arr[:2, ::2]
print ("Array with first 2 rows and"
    " alternate columns(0 and 2):\n", sliced_arr)
 
# Printing elements at
# specific Indices
Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", Index_arr)

Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


Basic Array Operations :

In [50]:
import numpy as np
 
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])
               
# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)
 
# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)
 
# sum of array elements
# Performing Unary operations
print ("\nSum of all array "
       "elements: ", a.sum())
 
# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)

Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


Constructing a Datatype Object :

In [51]:
import numpy as np
 
# Integer datatype
# guessed by Numpy
x = np.array([1, 2])  
print("Integer Datatype: ")
print(x.dtype)         
 
# Float datatype
# guessed by Numpy
x = np.array([1.0, 2.0]) 
print("\nFloat Datatype: ")
print(x.dtype)  
 
# Forced Datatype
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)

Integer Datatype: 
int32

Float Datatype: 
float64

Forcing a Datatype: 
int64


Math Operations on DataType array :


In [52]:
import numpy as np
 
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ")
print(Sum)
 
# Addition of all Array elements
# using predefined sum method
Sum1 = np.sum(arr1)
print("\nAddition of Array elements: ")
print(Sum1)
 
# Square root of Array
Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ")
print(Sqrt)
 
# Transpose of Array
# using In-built function 'T'
Trans_arr = arr1.T
print("\nTranspose of Array: ")
print(Trans_arr)

Addition of Two Arrays: 
[[ 7. 13.]
 [ 4. 14.]]

Addition of Array elements: 
19.0

Square root of Array1 elements: 
[[2.         2.64575131]
 [1.41421356 2.44948974]]

Transpose of Array: 
[[4. 2.]
 [7. 6.]]


Dimensionalities of array:

0D (zer-dimensional) =  Scalar – A single element

1D (one-dimensional) =  Vector- A list of integers

2D (two-dimensional) =  Matrix- A spreadsheet of data

3D (three-dimensional) = Tensor- Storing a color image


Create Array Object :


In [55]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


Create NumPy Array from a List :

1. The following example shows how to initialize a array from a list. 

In [56]:
import numpy as np
li = [1,2,3,4]
numpyArr = np.array(li)
print(numpyArr)

[1 2 3 4]


2. Let’s take an example to check whether the numpyArr is a NumPy object or not. In this example, we are using the array() function to convert the list into a NumPy array and then check if it’s a NumPy object or not.

In [58]:
import numpy as np

li = [1,2,3,4]
numpyArr = np.array(li)

print("li =", li, "and type(li) =", type(li))
print("numpyArr =", numpyArr, "and type(numpyArr) =", type(numpyArr))

li = [1, 2, 3, 4] and type(li) = <class 'list'>
numpyArr = [1 2 3 4] and type(numpyArr) = <class 'numpy.ndarray'>


Create a NumPy Array from a Tuple :

In [60]:
import numpy as np

tup = (1,2,3,4)
numpyArr = np.array(tup)

print("tup =", tup, "and type(tup) =", type(tup))
print("numpyArr =", numpyArr, "and type(numpyArr) =", type(numpyArr))

tup = (1, 2, 3, 4) and type(tup) = <class 'tuple'>
numpyArr = [1 2 3 4] and type(numpyArr) = <class 'numpy.ndarray'>


One Dimensional Array:

In [62]:
import numpy as np

# creating list
list = [1, 2, 3, 4]

# creating numpy array
sample_array = np.array(list)

print("List in python : ", list)

print("Numpy Array in python :",
      sample_array)

List in python :  [1, 2, 3, 4]
Numpy Array in python : [1 2 3 4]


Multi-Dimensional Array:

In [63]:
import numpy as np

# creating list 
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]

# creating numpy array
sample_array = np.array([list_1, 
                         list_2,
                         list_3])

print("Numpy multi dimensional array in python\n",
      sample_array)

Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Anatomy of an array :

1. Axis: The Axis of an array describes the order of the indexing into the array.

Axis 0 = one dimensional

Axis 1 = Two dimensional

Axis 2 = Three dimensional 

2. Shape: The number of elements along with each axis. It is from a tuple.

In [65]:
import numpy as np

# creating list 
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]

# creating numpy array
sample_array = np.array([list_1,
                         list_2,
                         list_3])
arrays = sample_array.shape

print("Numpy array :")
print(sample_array)

# print shape of the array
print("Shape of the array :",arrays)

Numpy array :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of the array : (3, 4)


3. Rank: The rank of an array is simply the number of axes (or dimensions) it has.

4. Data type objects (dtype):

 Data type objects (dtype) is an instance of numpy.dtype class. It describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted.

In [67]:
# Import module
import numpy as np

# Creating the array 
sample_array_1 = np.array([[0, 4, 2]])

sample_array_2 = np.array([[0.2, 0.4, 2.4]])

# display data type
print("Data type of the array 1 :",
      sample_array_1.dtype)

print("Data type of array 2 :",
      sample_array_2.dtype)


Data type of the array 1 : int32
Data type of array 2 : float64


* numpy.fromiter(): The fromiter() function create a new one-dimensional array from an iterable object.

  Syntax: numpy.fromiter(iterable, dtype, count=-1)

In [68]:
import numpy as np

# iterable
iterable = (a*a for a in range(8))

arr = np.fromiter(iterable, float)

print("fromiter() array :",arr)

fromiter() array : [ 0.  1.  4.  9. 16. 25. 36. 49.]


In [69]:
import numpy as np

var = "Geekforgeeks"

arr = np.fromiter(var, dtype = 'U2')

print("fromiter() array :",
      arr)

fromiter() array : ['G' 'e' 'e' 'k' 'f' 'o' 'r' 'g' 'e' 'e' 'k' 's']


* numpy.empty(): This function create a new array of given shape and type, without initializing value.

In [70]:
import numpy as np

np.empty([4, 3],
         dtype = np.int32,
         order = 'f')

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

numpy.ones(): This function is used to get a new array of given shape and type, filled with ones(1).

Syntax: numpy.ones(shape, dtype=None, order=’C’)

In [71]:
import numpy as np

np.ones([4, 3],
        dtype = np.int32,
        order = 'f')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [72]:
import numpy as np
np.zeros([4, 3],  #zeros
         dtype = np.int32,
         order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [73]:
import numpy as np
 
dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (2,))])
 
# x is a structured array with names and marks of students.
# Data type of name of the student is np.unicode_ and 
# data type of marks is np.float(64)
x = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0))], dtype=dt)
 
print(x[1])
print("Grades of John are: ",x[1]['grades'])
print("Names are: ",x['name'])

('John', [6., 7.])
Grades of John are:  [6. 7.]
Names are:  ['Sarah' 'John']
