Linear Algebra :

In [1]:
# Importing numpy as np
import numpy as np
 
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [2]:
# Python program explaining
# eigh() function
 
from numpy import linalg as geek
 
# Creating an array using array 
# function
a = np.array([[1, -2j], [2j, 5]])
 
print("Array is :",a)
 
# calculating an eigen value
# using eigh() function
c, d = geek.eigh(a)
 
print("Eigen value is :", c)
print("Eigen value is :", d)

Array is : [[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]]
Eigen value is : [0.17157288 5.82842712]
Eigen value is : [[-0.92387953-0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]


numpy.linalg.eig(a) : 

This function is used to compute the eigenvalues and right eigenvectors of a square array.

In [3]:
# eig() function
 
from numpy import linalg as geek
 
# Creating an array using diag 
# function
a = np.diag((1, 2, 3))
 
print("Array is :",a)
 
# calculating an eigen value
# using eig() function
c, d = geek.eig(a)
 
print("Eigen value is :",c)
print("Eigen value is :",d)

Array is : [[1 0 0]
 [0 2 0]
 [0 0 3]]
Eigen value is : [1. 2. 3.]
Eigen value is : [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Python Program illustrating
# numpy.dot() method
 
import numpy as geek
 
# Scalars
product = geek.dot(5, 4)
print("Dot Product of scalar values  : ", product)
 
# 1D array
vector_a = 2 + 3j
vector_b = 4 + 5j
 
product = geek.dot(vector_a, vector_b)
print("Dot Product  : ", product)

Dot Product of scalar values  :  20
Dot Product  :  (-7+22j)


In [5]:
# Python Program illustrating
# numpy.vdot() method
 
import numpy as geek
 
# 1D array
vector_a = 2 + 3j
vector_b = 4 + 5j
 
product = geek.vdot(vector_a, vector_b)
print("Dot Product  : ", product)

Dot Product  :  (23-2j)


numpy.linalg.solve() : 

Solve a linear matrix equation, or system of linear scalar equations.Computes the “exact” solution, x, of the well-determined, i.e., full rank, linear matrix equation ax = b.

In [6]:
# numpy.linalg.solve() method
 
import numpy as np
 
# Creating an array using array
# function
a = np.array([[1, 2], [3, 4]])
 
# Creating an array using array
# function
b = np.array([8, 18])
 
print(("Solution of linear equations:", 
      np.linalg.solve(a, b)))

('Solution of linear equations:', array([2., 3.]))


numpy.linalg.lstsq() :

Return the least-squares solution to a linear matrix equation.Solves the equation a x = b by computing a vector x that minimizes the Euclidean 2-norm || b – a x ||^2. The equation may be under-, well-, or over- determined (i.e., the number of linearly independent rows of a can be less than, equal to, or greater than its number of linearly independent columns). If a is square and of full rank, then x (but for round-off error) is the “exact” solution of the equation.

# Python Program illustrating
# numpy.linalg.lstsq() method
 
 
import numpy as np
import matplotlib.pyplot as plt
 
# x co-ordinates
x = np.arange(0, 9)
A = np.array([x, np.ones(9)])
 
# linearly generated sequence
y = [19, 20, 20.5, 21.5, 22, 23, 23, 25.5, 24]
# obtaining the parameters of regression line
w = np.linalg.lstsq(A.T, y)[0] 
 
# plotting the line
line = w[0]*x + w[1] # regression line
plt.plot(x, line, 'r-')
plt.plot(x, y, 'o')
plt.show()

numpy.linalg.det() : 

Compute the determinant of an array.

In [8]:
# Python Program illustrating
# numpy.linalg.det() method
 
import numpy as np
 
# creating an array using 
# array method
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
 
print(("\nDeterminant of A:"
     , np.linalg.det(A)))

('\nDeterminant of A:', -306.0)


numpy.trace() :

Return the sum along diagonals of the array.If a is 2-D, the sum along its diagonal with the given offset is returned

In [9]:
import numpy as np
 
# creating an array using 
# array method
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
 
print("\nTrace of A:", np.trace(A))


Trace of A: 11


Get the QR factorization of a given NumPy array :

In [10]:
# Import numpy package 
import numpy as np 

# Create a numpy array 
arr = np.array([[10,22],[13,6]]) 

# Find the QR factor of array 
q, r = np.linalg.qr(arr) 

# Print the result 
print("Decomposition of matrix:") 
print( "q=\n", q, "\nr=\n", r)


Decomposition of matrix:
q=
 [[-0.60971076 -0.79262399]
 [-0.79262399  0.60971076]] 
r=
 [[-16.40121947 -18.16938067]
 [  0.         -13.7794632 ]]


In [11]:
# Import numpy package 
import numpy as np 

# Create a numpy array 
arr = np.array([[0, 1], [1, 0], [1, 1], [2, 2]]) 

# Find the QR factor of array 
q, r = np.linalg.qr(arr) 

# Print the result 
print("Decomposition of matrix:") 
print( "q=\n", q, "\nr=\n", r) 


Decomposition of matrix:
q=
 [[ 0.          0.73854895]
 [-0.40824829 -0.61545745]
 [-0.40824829  0.12309149]
 [-0.81649658  0.24618298]] 
r=
 [[-2.44948974 -2.04124145]
 [ 0.          1.3540064 ]]


In [12]:
# Import numpy package 
import numpy as np 

# Create a numpy array 
arr = np.array([[5, 11, -15], [12, 34, -51], 
				[-24, -43, 92]], dtype=np.int32) 

# Find the QR factor of array 
q, r = np.linalg.qr(arr) 

# Print the result 
print("Decomposition of matrix:") 
print( "q=\n", q, "\nr=\n", r)


Decomposition of matrix:
q=
 [[-0.18318583 -0.08610905  0.97929984]
 [-0.43964598 -0.88381371 -0.15995231]
 [ 0.87929197 -0.45984624  0.12404465]] 
r=
 [[-27.29468813 -54.77256208 106.06459346]
 [  0.         -11.22347731   4.06028083]
 [  0.           0.           4.88017756]]


How to get the magnitude of a vector in NumPy :

In [13]:
# program to compute magnitude of a vector

# importing required libraries
import numpy
import math

# function definition to compute magnitude o f the vector
def magnitude(vector): 
	return math.sqrt(sum(pow(element, 2) for element in vector))

# displaying the original vector
v = numpy.array([0, 1, 2, 3, 4])
print('Vector:', v)

# computing and displaying the magnitude of the vector
print('Magnitude of the Vector:', magnitude(v))


Vector: [0 1 2 3 4]
Magnitude of the Vector: 5.477225575051661


In [14]:
# program to compute magnitude of a vector

# importing required libraries
import numpy
import math

# function definition to compute magnitude o f the vector
def magnitude(vector): 
	return math.sqrt(sum(pow(element, 2) for element in vector))

# computing and displaying the magnitude of the vector
print('Magnitude of the Vector:', magnitude(numpy.array([1, 2, 3])))


Magnitude of the Vector: 3.7416573867739413


In [15]:
# program to compute magnitude of a vector

# importing required libraries
import numpy

# displaying the original vector
v = numpy.array([1, 2, 3])
print('Vector:', v)

# computing and displaying the magnitude of
# the vector using norm() method
print('Magnitude of the Vector:', numpy.linalg.norm(v))


Vector: [1 2 3]
Magnitude of the Vector: 3.7416573867739413


In [16]:
# program to compute the nth order of the 
# magnitude of a vector

# importing required libraries
import numpy

# displaying the original vector
v = numpy.array([0, 1, 2, 3, 4])
print('Vector:', v)

# computing and displaying the magnitude of the vector
print('Magnitude of the Vector:', numpy.linalg.norm(v))

# Computing the nth order of the magnitude of vector
print('ord is 0: ', numpy.linalg.norm(v, ord = 0))
print('ord is 1: ', numpy.linalg.norm(v, ord = 1))
print('ord is 2: ', numpy.linalg.norm(v, ord = 2))
print('ord is 3: ', numpy.linalg.norm(v, ord = 3))
print('ord is 4: ', numpy.linalg.norm(v, ord = 4))


Vector: [0 1 2 3 4]
Magnitude of the Vector: 5.477225575051661
ord is 0:  4.0
ord is 1:  10.0
ord is 2:  5.477225575051661
ord is 3:  4.641588833612778
ord is 4:  4.337613136533361


How to compute the eigenvalues and right eigenvectors of a given square array using NumPY :

In [18]:
# importing numpy library 
import numpy as np 

# create numpy 2d-array 
m = np.array([[1, 2], 
			[2, 3]]) 

print("Printing the Original square array:\n", 
	m) 

# finding eigenvalues and eigenvectors 
w, v = np.linalg.eig(m) 

# printing eigen values 
print("Printing the Eigen values of the given square array:\n", 
	w) 

# printing eigen vectors 
print("Printing Right eigenvectors of the given square array:\n",
	v)


Printing the Original square array:
 [[1 2]
 [2 3]]
Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]
Printing Right eigenvectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [19]:
# importing numpy library 
import numpy as np 

# create numpy 2d-array 
m = np.array([[1, 2, 3], 
			[2, 3, 4], 
			[4, 5, 6]]) 

print("Printing the Original square array:\n", 
	m) 

# finding eigenvalues and eigenvectors 
w, v = np.linalg.eig(m) 

# printing eigen values 
print("Printing the Eigen values of the given square array:\n", 
	w) 

# printing eigen vectors 
print("Printing Right eigenvectors of the given square array:\n", 
	v) 


Printing the Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]
Printing the Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01 -1.09042184e-16]
Printing Right eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]
