NumPy Copy and View of Array :

View of Array in NumPy :

The view is just a view of the original ndarray and the view does not own the data. 

You can create an array view using the view() function of the NumPy library.

This is also known as Shallow Copy. 

In [1]:
import numpy as np  
# creating array  
arr = np.array([2, 4, 6, 8, 10])  
# creating view  
v = arr.view()  
# both arr and v have different id  
print("id of arr", id(arr))  
print("id of v", id(v))  
# changing original array  
# will effect view  
arr[0] = 12
# printing array and view  
print("original array- ", arr)  
print("view- ", v)

id of arr 2427759931728
id of v 2427759932208
original array-  [12  4  6  8 10]
view-  [12  4  6  8 10]


Copy of Array in NumPy :

The copy is completely a new array and the copy owns the data. 

You can create a copy of an array using the copy() function of the NumPy library.

This is also known as Deep Copy.

In [2]:
import numpy as np 
  
# creating array 
arr = np.array([2, 4, 6, 8, 10]) 
  
# creating copy of array 
c = arr.copy() 
  
# both arr and c have different id 
print("id of arr", id(arr)) 
print("id of c", id(c)) 
  
# changing original array 
# this will not effect copy 
arr[0] = 12
  
# printing array and copy 
print("original array- ", arr) 
print("copy- ", c) 

id of arr 2427759932112
id of c 2427760235920
original array-  [12  4  6  8 10]
copy-  [ 2  4  6  8 10]


Assigning Array to Variable :

In [3]:
import numpy as np 
  
# creating array 
arr = np.array([2, 4, 6, 8, 10]) 
  
# assigning arr to nc 
nc = arr 
  
# both arr and nc have same id 
print("id of arr", id(arr)) 
print("id of nc", id(nc)) 
  
# updating nc 
nc[0]= 12
  
# printing the values 
print("original array- ", arr) 
print("assigned array- ", nc) 

id of arr 2427760235728
id of nc 2427760235728
original array-  [12  4  6  8 10]
assigned array-  [12  4  6  8 10]


check if the Array is a View or a Copy :

In [6]:
import numpy as np 
  
# creating array 
arr = np.array([2, 4, 6, 8, 10]) 
  
# creating copy of array 
c = arr.copy() 
  
# creating view of array 
v = arr.view() 
  
# printing base attribute of copy and view 
print(c.base) 
print("-----------")
print(v.base) 

None
-----------
[ 2  4  6  8 10]


Copy 1D Numpy Arrays into Another Using np.copy() Function :

In [7]:
# importing Numpy package
import numpy as np
 
# Creating a numpy array using np.array()
org_array = np.array([1.54, 2.99, 3.42, 4.87, 6.94,
                      8.21, 7.65, 10.50, 77.5])
 
print("Original array: ")
 
# printing the Numpy array
print(org_array)
 
# Now copying the org_array to copy_array
# using np.copy() function
copy_array = np.copy(org_array)
 
print("\nCopied array: ")
 
# printing the copied Numpy array
print(copy_array)

Original array: 
[ 1.54  2.99  3.42  4.87  6.94  8.21  7.65 10.5  77.5 ]

Copied array: 
[ 1.54  2.99  3.42  4.87  6.94  8.21  7.65 10.5  77.5 ]


Copy Given 2-D Array to Another Array Using np.copy() Function :

In [8]:
import numpy as np
 
# Creating a 2-D numpy array using np.array()
org_array = np.array([[23, 46, 85],
                      [43, 56, 99],
                      [11, 34, 55]])
 
print("Original array: ")
 
# printing the Numpy array
print(org_array)
 
# Now copying the org_array to copy_array
# using np.copy() function
copy_array = np.copy(org_array)
 
print("\nCopied array: ")
 
# printing the copied Numpy array
print(copy_array)

Original array: 
[[23 46 85]
 [43 56 99]
 [11 34 55]]

Copied array: 
[[23 46 85]
 [43 56 99]
 [11 34 55]]


NumPy Array Copy Using Assignment Operator :

In [9]:
import numpy as np
 
# Create a 2-D Numpy array using np.array()
org_array = np.array([[99, 22, 33],
                      [44, 77, 66]])
 
# Copying org_array to copy_array
# using Assignment operator
copy_array = org_array
 
# modifying org_array
org_array[1, 2] = 13
 
# checking if copy_array has remained the same
 
# printing original array
print('Original Array: \n', org_array)
 
# printing copied array
print('\nCopied Array: \n', copy_array)

Original Array: 
 [[99 22 33]
 [44 77 13]]

Copied Array: 
 [[99 22 33]
 [44 77 13]]


Appending a Single Value to a 1D Array :

In [10]:
import numpy as np
 
# creating an array
arr = np.array([1, 8, 3, 3, 5])
print('Original Array : ', arr)
 
# appending to the array
arr = np.append(arr, [7])
print('Array after appending : ', arr)

Original Array :  [1 8 3 3 5]
Array after appending :  [1 8 3 3 5 7]


Appending Another Array at the End of a 1D Array :

In [11]:
import numpy as np
 
# creating an array
arr1 = np.array([1, 2, 3])
print('First array is : ', arr1)
 
# creating another array
arr2 = np.array([4, 5, 6])
print('Second array is : ', arr2)
 
# appending arr2 to arr1
arr = np.append(arr1, arr2)
print('Array after appending : ', arr)

First array is :  [1 2 3]
Second array is :  [4 5 6]
Array after appending :  [1 2 3 4 5 6]


Appending Values at the End Using Concatenation :

In [14]:
import numpy as np
 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
 
combined = np.concatenate((arr1, arr2), axis=0)
print(combined)

[[1 2]
 [3 4]
 [5 6]]


Appending with a Different Array Type :

In [15]:
import numpy as np
 
arr = np.array([1, 2, 3])
arr_float = np.array([4.0, 5.0])
 
combined = np.append(arr, arr_float)
print(combined)  # Output: [1. 2. 3. 4. 5.]

[1. 2. 3. 4. 5.]


Appending Using List Comprehension and numpy.concatenate :

In [16]:
import numpy as np
 
arr = np.array([1, 2, 3, 4, 5])
values_to_append = [np.array([6, 7]), np.array([8, 9])]
combined = np.concatenate([arr] + values_to_append)
print(combined)

[1 2 3 4 5 6 7 8 9]


Appending Values at the End of the N-Dimensional Array :

In [17]:
import numpy as np
 
# create an array
arr = np.arange(1, 13).reshape(2, 6)
print('Original Array')
print(arr, '\n')
 
# create another array which is
# to be appended column-wise
col = np.arange(5, 11).reshape(1, 6)
print('Array to be appended column wise')
print(col)
arr_col = np.append(arr, col, axis=0)
print('Array after appending the values column wise')
print(arr_col, '\n')
 
# create an array which is
# to be appended row wise
row = np.array([1, 2]).reshape(2, 1)
print('Array to be appended row wise')
print(row)
arr_row = np.append(arr, row, axis=1)
print('Array after appending the values row wise')
print(arr_row)

Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

Array to be appended column wise
[[ 5  6  7  8  9 10]]
Array after appending the values column wise
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]] 

Array to be appended row wise
[[1]
 [2]]
Array after appending the values row wise
[[ 1  2  3  4  5  6  1]
 [ 7  8  9 10 11 12  2]]


swap columns of a given NumPy array :

In [19]:
import numpy as np
 
 
# creating array with shape(4,3)
my_array = np.arange(12).reshape(4, 3)
print("Original array:")
print(my_array)
 
# swapping the column with index of 
# original array
my_array[:, [1, 2]] = my_array[:, [2, 1]]
print("After swapping arrays the last column and first column:")
print(my_array)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After swapping arrays the last column and first column:
[[ 0  2  1]
 [ 3  5  4]
 [ 6  8  7]
 [ 9 11 10]]


Swapping the column of an array with the user chooses :

In [20]:
import numpy as np
 
 
# Creating array
my_array = np.arange(12).reshape(4, 3)
print("Original Array : ")
print(my_array)
# creating function for swap
 
def Swap(arr, start_index, last_index):
    arr[:, [start_index, last_index]] = arr[:, [last_index, start_index]]
 
# passing parameter into the function
Swap(my_array, 0, 1)
print(" After Swapping :")
print(my_array)

Original Array : 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
 After Swapping :
[[ 1  0  2]
 [ 4  3  5]
 [ 7  6  8]
 [10  9 11]]


Insert a new axis within a NumPy array :

Using numpy.newaxis() :

In [21]:
import numpy as np
 
arr = np.arange(5*5).reshape(5, 5)
print(arr.shape)
 
# promoting 2D array to a 5D array
# arr[None, ..., None, None]
arr_5D = arr[np.newaxis, ..., np.newaxis, np.newaxis]
 
print(arr_5D.shape)

(5, 5)
(1, 5, 5, 1, 1)


Using numpy.expand_dims() :

In [22]:
import numpy as np
 
x = np.zeros((3, 4))
y = np.expand_dims(x, axis=1).shape
print(y)

(3, 1, 4)


Simultaneously Insert Many New Axes in the Array :

In [24]:
import numpy as np

arr = np.arange(5*5).reshape(5,5)
print(arr.shape)

newaxes = (0, 3, -1)
arr_5D = np.expand_dims(arr, axis=newaxes)
print(arr_5D.shape)


(5, 5)
(1, 5, 5, 1, 1)


Using numpy.reshape() for a Single Axis :

In [27]:
import numpy as np
arr = np.arange(6)
arr_reshape = arr.reshape((2, 3))
print(arr_reshape)

[[0 1 2]
 [3 4 5]]


numpy.hstack() in Python :

In [28]:
import numpy as geek 
  
# input array 
in_arr1 = geek.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = geek.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)  
  
# Stacking the two arrays horizontally 
out_arr = geek.hstack((in_arr1, in_arr2)) 
print ("Output horizontally stacked array:\n ", out_arr) 

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


In [29]:
import numpy as geek 
  
# input array 
in_arr1 = geek.array([[ 1, 2, 3], [ -1, -2, -3]] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = geek.array([[ 4, 5, 6], [ -4, -5, -6]] ) 
print ("2nd Input array : \n", in_arr2)  
  
# Stacking the two arrays horizontally 
out_arr = geek.hstack((in_arr1, in_arr2)) 
print ("Output stacked array :\n ", out_arr) 

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]]


numpy.vstack() in python :

In [30]:
import numpy as geek 
  
# input array 
in_arr1 = geek.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = geek.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)  
  
# Stacking the two arrays vertically 
out_arr = geek.vstack((in_arr1, in_arr2)) 
print ("Output vertically stacked array:\n ", out_arr) 

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]


In [31]:
import numpy as geek 
  
# input array 
in_arr1 = geek.array([[ 1, 2, 3], [ -1, -2, -3]] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = geek.array([[ 4, 5, 6], [ -4, -5, -6]] ) 
print ("2nd Input array : \n", in_arr2)  
  
# Stacking the two arrays vertically 
out_arr = geek.vstack((in_arr1, in_arr2)) 
print ("Output stacked array :\n ", out_arr) 

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]
 [-4 -5 -6]]


Joining NumPy Array :

Using numpy.concatenate() :

The concatenate function in NumPy joins two or more arrays along a specified axis. 

In [33]:
import numpy as np 
  
array_1 = np.array([1, 2]) 
array_2 = np.array([3, 4]) 
  
array_new = np.concatenate((array_1, array_2)) 
print(array_new) 

[1 2 3 4]


In [34]:
import numpy as np 
  
array_1 = np.array([[1, 2], [3, 4]]) 
array_2 = np.array([[5, 6], [7, 8]]) 
  
array_new = np.concatenate((array_1, array_2), axis=1) 
print(array_new) 

[[1 2 5 6]
 [3 4 7 8]]


Using numpy.stack() :

The stack() function of NumPy joins two or more arrays along a new axis.

In [35]:
import numpy as np 
  
array_1 = np.array([1, 2, 3, 4]) 
array_2 = np.array([5, 6, 7, 8]) 
  
array_new = np.stack((array_1, array_2), axis=1) 
print(array_new) 

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


numpy.block() :

numpy.block is used to create nd-arrays from nested blocks of lists.

In [38]:
import numpy as np 
  
block_1 = np.array([[1, 1], [1, 1]]) 
block_2 = np.array([[2, 2, 2], [2, 2, 2]]) 
block_3 = np.array([[3, 3], [3, 3], [3, 3]]) 
block_4 = np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4]]) 
  
block_new = np.block([ 
    [block_1, block_2], 
    [block_3, block_4] 
]) 
  
print(block_new) 

[[1 1 2 2 2]
 [1 1 2 2 2]
 [3 3 4 4 4]
 [3 3 4 4 4]
 [3 3 4 4 4]]


Combining a one and a two-dimensional NumPy Array :

In [39]:
import numpy as np 
  
num_1d = np.arange(5) 
print("One dimensional array:") 
print(num_1d) 
  
num_2d = np.arange(10).reshape(2,5) 
print("\nTwo dimensional array:") 
print(num_2d) 
  
# Combine 1-D and 2-D arrays and display  
# their elements using numpy.nditer()  
for a, b in np.nditer([num_1d, num_2d]): 
    print("%d:%d" % (a, b),)

One dimensional array:
[0 1 2 3 4]

Two dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


In [40]:
import numpy as np 
  
num_1d = np.arange(7) 
print("One dimensional array:") 
print(num_1d) 
  
num_2d = np.arange(21).reshape(3,7) 
print("\nTwo dimensional array:") 
print(num_2d) 
  
# Combine 1-D and 2-D arrays and display  
# their elements using numpy.nditer()  
for a, b in np.nditer([num_1d, num_2d]): 
    print("%d:%d" % (a, b),)

One dimensional array:
[0 1 2 3 4 5 6]

Two dimensional array:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
0:0
1:1
2:2
3:3
4:4
5:5
6:6
0:7
1:8
2:9
3:10
4:11
5:12
6:13
0:14
1:15
2:16
3:17
4:18
5:19
6:20


In [41]:
import numpy as np 
  
num_1d = np.arange(2) 
print("One dimensional array:") 
print(num_1d) 
  
num_2d = np.arange(12).reshape(6,2) 
print("\nTwo dimensional array:") 
print(num_2d) 
  
# Combine 1-D and 2-D arrays and display 
# their elements using numpy.nditer()  
for a, b in np.nditer([num_1d, num_2d]): 
    print("%d:%d" % (a, b),)

One dimensional array:
[0 1]

Two dimensional array:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
0:0
1:1
0:2
1:3
0:4
1:5
0:6
1:7
0:8
1:9
0:10
1:11


Numpy np.ma.concatenate() method :

In [42]:
import numpy as np 
import numpy.ma as ma 
  
gfg1 = np.array([1, 2, 3]) 
gfg2 = np.array([4, 5, 6]) 
  
# using np.ma.concatenate() method 
gfg = ma.concatenate([gfg1, gfg2]) 
  
print(gfg) 

[1 2 3 4 5 6]


In [46]:
import numpy as np 
import numpy.ma as ma 
  
gfg1 = np.array([11, 22, 33]) 
gfg2 = np.array([41, 52, 63]) 
  
# using np.ma.concatenate() method 
gfg = ma.concatenate([[gfg1], [gfg2]]) 
  
print(gfg) 

[[11 22 33]
 [41 52 63]]


Numpy dstack() method :

In [47]:
import numpy as np 
  
gfg1 = np.array([1, 2, 3]) 
gfg2 = np.array([4, 5, 6]) 
  
# using numpy.dstack() method 
print(np.dstack((gfg1, gfg2))) 

[[[1 4]
  [2 5]
  [3 6]]]


In [48]:
import numpy as np 
  
gfg1 = np.array([[10], [2], [13]]) 
gfg2 = np.array([[41], [55], [6]]) 
  
# using numpy.dstack() method 
print(np.dstack((gfg1, gfg2))) 

[[[10 41]]

 [[ 2 55]]

 [[13  6]]]


NumPy Splitting Array :

In [51]:
import numpy as np
Arr = np.array([1, 2, 3, 4, 5, 6])
array = np.array_split(Arr, 3)
print(array)

[array([1, 2]), array([3, 4]), array([5, 6])]


Splitting Arrays Into Equal Parts using numpy.split() :

In [52]:
import numpy as np
 
# Creating an example array
array = np.arange(6)
 
# Splitting the array into 2 equal parts along the first axis (axis=0)
result = np.split(array, 2)
 
print("Array:")
print(array)
print("\nResult after numpy.split():")
print(result)

Array:
[0 1 2 3 4 5]

Result after numpy.split():
[array([0, 1, 2]), array([3, 4, 5])]


Unequal Splitting of Arrays using numpy.array_split() :

In [56]:
import numpy as np
 
# Creating an example array
array = np.arange(13)
 
# Splitting the array into 4 unequal parts along the first axis (axis=0)
result = np.array_split(array, 4)
 
print("Array:")
print(array)
print("\nResult after numpy.array_split():")
print(result)

Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]

Result after numpy.array_split():
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


Splitting NumPy 2D Arrays :

In [58]:
import numpy as np
 
# Creating a 2D array
array = np.array([[3, 2, 1], [8, 9, 7], [4, 6, 5]])
 
# Splitting the array into 3 equal parts along the second axis (axis=1)
result = np.split(array, 3, axis=1)
 
print("2D Array:")
print(array)
print("\nResult after numpy.split() along axis=1:")
print(result)

2D Array:
[[3 2 1]
 [8 9 7]
 [4 6 5]]

Result after numpy.split() along axis=1:
[array([[3],
       [8],
       [4]]), array([[2],
       [9],
       [6]]), array([[1],
       [7],
       [5]])]


Vertical Splitting of Arrays using numpy.vsplit() :

In [59]:
import numpy as np
 
# Creating an example matrix
matrix = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]])
 
# Vertical splitting into 2 subarrays along axis=0
result = np.vsplit(matrix, 2)
 
print("Matrix:")
print(matrix)
print("\nResult after numpy.vsplit():")
print(result)

Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Result after numpy.vsplit():
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


Horizontal Splitting of Arrays using numpy.hsplit() :

In [60]:
import numpy as np
 
# Creating an example 2D array
array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])
 
# Horizontal splitting into 2 subarrays along axis=1
result = np.hsplit(array, 2)
 
print("2D Array:")
print(array)
print("\nResult after numpy.hsplit():")
print(result)

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result after numpy.hsplit():
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


Splitting Arrays Along the Third Axis using numpy.dsplit() :

In [61]:
import numpy as np

# Creating an example 3D array
original_3d_array = np.arange(24).reshape((2, 3, 4))

# Splitting along axis=2 (third axis)
result = np.dsplit(original_3d_array, 2)

print("Original 3D Array:")
print(original_3d_array)
print("\nResult after numpy.dsplit():")
print(result)


Original 3D Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Result after numpy.dsplit():
[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


compare two NumPy arrays :

In [62]:
import numpy as np
 
an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])
 
comparison = an_array == another_array
equal_arrays = comparison.all()
 
print(equal_arrays)

True


In [63]:
import numpy as np
 
 
a = np.array([101, 99, 87])
b = np.array([897, 97, 111])
 
print("Array a: ", a)
print("Array b: ", b)
 
print("a > b")
print(np.greater(a, b))
 
print("a >= b")
print(np.greater_equal(a, b))
 
print("a < b")
print(np.less(a, b))
 
print("a <= b")
print(np.less_equal(a, b))

Array a:  [101  99  87]
Array b:  [897  97 111]
a > b
[False  True False]
a >= b
[False  True False]
a < b
[ True False  True]
a <= b
[ True False  True]


Using array_equal()  :

In [64]:
import numpy as np
 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
 
 
# Comparing the arrays
if np.array_equal(arr1, arr2):
    print("Equal")
else:
    print("Not Equal")

Equal


The union of two NumPy arrays :

In [65]:
import numpy as np 
  
  
arr1 = np.array([10, 20, 30, 40]) 
print("array1 ", arr1) 
  
arr2 = np.array([20, 40, 60, 80]) 
print("array2 ", arr2) 
  
# print union of the two arrays 
print("Union of two arrays :", np.union1d(arr1, arr2)) 

array1  [10 20 30 40]
array2  [20 40 60 80]
Union of two arrays : [10 20 30 40 60 80]


In [66]:
import numpy as np 
  
  
# 2-d array 
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) 
print("array1 ") 
print(arr1) 
  
arr2 = np.array([0, 5, 10]) 
print("array2 ", arr2) 
  
# print union of 2-d array and 1-d array 
print("Union of two arrays", np.union1d(arr1, arr2)) 

array1 
[[1 2 3]
 [4 5 6]]
array2  [ 0  5 10]
Union of two arrays [ 0  1  2  3  4  5  6 10]


If we want to find union of more than two arrays, then we can find that by using functools.reduce function.

In [67]:
import numpy as np 
from functools import reduce
  
  
array = reduce(np.union1d, ([1, 2, 3], [1, 3, 5], 
                            [2, 4, 6], [0, 0, 0])) 
print("Union ", array) 

Union  [0 1 2 3 4 5 6]


unique rows in a NumPy array :

In [71]:
import numpy as np
 
# Create a 2D numpy array
arr2D = np.array([[11, 11, 12, 11],
                     [13, 11, 12, 11],
                     [16, 11, 12, 11],
                     [11, 11, 12, 11]])
 
print('Original Array :' ,
      arr2D, sep = '\n')
 
uniqueRows = np.unique(arr2D)  # there is no axis so it gives unique number only.it has axis means give the unique row
                        
 
# print the output result
print('Unique Rows:',
      uniqueRows, sep = '\n')

Original Array :
[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]
 [11 11 12 11]]
Unique Rows:
[11 12 13 16]


In [69]:
import numpy as np
 
# Create a 2D numpy array
arr2D = np.array([[11, 11, 12, 11],
                     [13, 11, 12, 11],
                     [16, 11, 12, 11],
                     [11, 11, 12, 11]])
 
uniqueRows = np.unique(arr2D, axis=0)
                        
 
# print the output result
print('Unique Rows:',
      uniqueRows, sep = '\n')

Unique Rows:
[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]]


In [72]:
# import library
import numpy as np
 
# Create a 2D numpy array
arr2D = np.array([[11, 11, 12, 11],
                     [13, 11, 12, 11],
                     [16, 11, 12, 11],
                     [11, 11, 12, 11]])
 
uniqueRows = np.unique(arr2D, axis=1)
                        
 
# print the output result
print('Unique Rows:',
      uniqueRows, sep = '\n')

Unique Rows:
[[11 11 12]
 [11 13 12]
 [11 16 12]
 [11 11 12]]


In [73]:
import numpy as np
 
# Create a 2D numpy array
arr2D = np.array([[11, 11, 12, 11],
                     [13, 11, 12, 11],
                     [16, 11, 12, 11],
                     [11, 11, 12, 11]])
 
uniqueRows = np.unique(arr2D, return_index=True)
                        
 
# print the output result
print('Unique Rows:',
      uniqueRows, sep = '\n')

Unique Rows:
(array([11, 12, 13, 16]), array([0, 2, 4, 8], dtype=int64))


In [74]:
import numpy as np
 
# Create a 2D numpy array
arr2D = np.array([[11, 11, 12, 11],
                     [13, 11, 12, 11],
                     [16, 11, 12, 11],
                     [11, 11, 12, 11]])
 
uniqueRows = np.unique(arr2D, return_inverse=True)
                        
 
# print the output result
print('Unique Rows:',
      uniqueRows, sep = '\n')

Unique Rows:
(array([11, 12, 13, 16]), array([0, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 0, 0, 1, 0], dtype=int64))


Numpy np.unique() method :

In [75]:
import numpy as np 
  
a = [1, 2, 2, 4, 3, 6, 4, 8] 
  
# using np.unique() method 
gfg = np.unique(a) 
  
print(gfg) 

[1 2 3 4 6 8]


In [76]:
import numpy as np 
  
a = [[10.2, 21.4, 3.6, 14.8], [1.0, 5.0, 10.0, 15.0]] 
  
# using np.unique() method 
gfg = np.unique(a) 
  
print(gfg) 

[ 1.   3.6  5.  10.  10.2 14.8 15.  21.4]


numpy.trim_zeros() in Python :

In [77]:
import numpy as geek  
  
gfg = geek.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0)) 
  
# without trim parameter 
# returns an array without leading and trailing zeros  
  
res = geek.trim_zeros(gfg) 
print(res) 

[ 1  5  7  0  6  2  9  0 10]


In [78]:
import numpy as geek  
gfg = geek.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0)) 
  
# without trim parameter 
# returns an array without any leading  zeros  
  
res = geek.trim_zeros(gfg, 'f') 
print(res) 

[ 1  5  7  0  6  2  9  0 10  0  0]


In [79]:
import numpy as geek  
gfg = geek.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0)) 
  
# without trim parameter 
# returns an array without any trailing  zeros  
  
res = geek.trim_zeros(gfg, 'b') 
print(res) 

[ 0  0  0  0  1  5  7  0  6  2  9  0 10]
