Binary Operations :

Binary operators :

Itacts on bits and performs bit by bit operation. Binary operation is simply a rule for combining two values to create a new value.

numpy.bitwise_and() : 

This function is used to Compute the bit-wise AND of two array element-wise. This function computes the bit-wise AND of the underlying binary representation of the integers in the input arrays.

In [1]:
# Python program explaining
# bitwise_and() function
 
import numpy as geek
in_num1 = 10
in_num2 = 11
 
print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2) 
   
out_num = geek.bitwise_and(in_num1, in_num2) 
print ("bitwise_and of 10 and 11 : ", out_num) 

Input  number1 :  10
Input  number2 :  11
bitwise_and of 10 and 11 :  10


In [2]:
import numpy as geek
 
in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 115]
  
print ("Input array1 : ", in_arr1) 
print ("Input array2 : ", in_arr2)
   
out_arr = geek.bitwise_and(in_arr1, in_arr2) 
print ("Output array after bitwise_and: ", out_arr) 

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Output array after bitwise_and:  [  2   0 113]


 
numpy.bitwise_or() : 

This function is used to Compute the bit-wise OR of two array element-wise. This function computes the bit-wise OR of the underlying binary representation of the integers in the input arrays

In [3]:
 
import numpy as geek
in_num1 = 10
in_num2 = 11
 
print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2) 
   
out_num = geek.bitwise_or(in_num1, in_num2) 
print ("bitwise_or of 10 and 11 : ", out_num) 

Input  number1 :  10
Input  number2 :  11
bitwise_or of 10 and 11 :  11


In [4]:
import numpy as geek
 
in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 115]
  
print ("Input array1 : ", in_arr1) 
print ("Input array2 : ", in_arr2)
   
out_arr = geek.bitwise_or(in_arr1, in_arr2) 
print ("Output array after bitwise_or: ", out_arr) 

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Output array after bitwise_or:  [  3  11 127]


 
numpy.bitwise_xor() :

This function is used to Compute the bit-wise XOR of two array element-wise. This function computes the bit-wise XOR of the underlying binary representation of the integers in the input arrays.

In [5]:
import numpy as geek
in_num1 = 10
in_num2 = 11
 
print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2) 
   
out_num = geek.bitwise_xor(in_num1, in_num2) 
print ("bitwise_xor of 10 and 11 : ", out_num) 

Input  number1 :  10
Input  number2 :  11
bitwise_xor of 10 and 11 :  1


In [6]:
import numpy as geek
 
in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 115]
  
print ("Input array1 : ", in_arr1) 
print ("Input array2 : ", in_arr2)
   
out_arr = geek.bitwise_xor(in_arr1, in_arr2) 
print ("Output array after bitwise_xor: ", out_arr) 

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Output array after bitwise_xor:  [ 1 11 14]


numpy.invert() : 

This function is used to Compute the bit-wise Inversion of an array element-wise. It computes the bit-wise NOT of the underlying binary representation of the integers in the input arrays.

In [7]:
import numpy as geek
in_num = 10
print ("Input  number : ", in_num)
   
out_num = geek.invert(in_num) 
print ("inversion of 10 : ", out_num) 

Input  number :  10
inversion of 10 :  -11


In [8]:
import numpy as geek
 
in_arr = [2, 0, 25]
print ("Input array : ", in_arr)
   
out_arr = geek.invert(in_arr) 
print ("Output array after inversion: ", out_arr) 

Input array :  [2, 0, 25]
Output array after inversion:  [ -3  -1 -26]


numpy.left_shift() : 

This function is used to Shift the bits of an integer to the left.The bits are shifted to the left by appending arr2 0s(zeroes) at the right of arr1

In [9]:
import numpy as geek
in_num = 5
bit_shift = 2
 
print ("Input  number : ", in_num)
print ("Number of bit shift : ", bit_shift ) 
   
out_num = geek.left_shift(in_num, bit_shift) 
print ("After left shifting 2 bit  : ", out_num) 

Input  number :  5
Number of bit shift :  2
After left shifting 2 bit  :  20


In [10]:
import numpy as geek
 
in_arr = [2, 8, 15]
bit_shift =[3, 4, 5]
  
print ("Input array : ", in_arr) 
print ("Number of bit shift : ", bit_shift)
   
out_arr = geek.left_shift(in_arr, bit_shift) 
print ("Output array after left shifting: ", out_arr) 

Input array :  [2, 8, 15]
Number of bit shift :  [3, 4, 5]
Output array after left shifting:  [ 16 128 480]


 
numpy.right_shift() :

This function is used to Shift the bits of an integer to the right.Because the internal representation of numbers is in binary format, this operation is equivalent to dividing arr1 by 2**arr2

In [11]:
import numpy as geek
in_num = 20
bit_shift = 2
 
print ("Input  number : ", in_num)
print ("Number of bit shift : ", bit_shift ) 
   
out_num = geek.right_shift(in_num, bit_shift) 
print ("After right shifting 2 bit  : ", out_num) 

Input  number :  20
Number of bit shift :  2
After right shifting 2 bit  :  5


In [12]:
import numpy as geek
 
in_arr = [24, 48, 16]
bit_shift =[3, 4, 2]
  
print ("Input array : ", in_arr) 
print ("Number of bit shift : ", bit_shift)
   
out_arr = geek.right_shift(in_arr, bit_shift) 
print ("Output array after right shifting: ", out_arr) 

Input array :  [24, 48, 16]
Number of bit shift :  [3, 4, 2]
Output array after right shifting:  [3 3 4]


numpy.binary_repr(number, width=None) : 

This function is used to represent binary form of the input number as a string.For negative numbers, if width is not given, a minus sign is added to the front. If width is given, the two’s complement of the number is returned, with respect to that width.
In a two’s-complement system, negative numbers are represented by the two’s complement of the absolute value

In [13]:
import numpy as geek
in_num = 10
 
print ("Input  number : ", in_num)
 
out_num = geek.binary_repr(in_num) 
print ("binary representation of 10 : ", out_num) 

Input  number :  10
binary representation of 10 :  1010


In [14]:
import numpy as geek
 
in_arr = [5, -8 ]
  
print ("Input array : ", in_arr) 
 
# binary representation of first array  
# element without using width parameter
out_num = geek.binary_repr(in_arr[0])
print("Binary representation of 5")
print ("Without using width parameter : ", out_num) 
 
# binary representation of first array
# element using width parameter
out_num = geek.binary_repr(in_arr[0], width = 5)
print ("Using width parameter: ", out_num) 
 
print("\nBinary representation of -8")
 
# binary representation of 2nd array
# element without using width parameter
out_num = geek.binary_repr(in_arr[1])
print ("Without using width parameter : ", out_num) 
 
# binary representation of 2nd array
# element  using width parameter
out_num = geek.binary_repr(in_arr[1], width = 5)
print ("Using width parameter : ", out_num) 

Input array :  [5, -8]
Binary representation of 5
Without using width parameter :  101
Using width parameter:  00101

Binary representation of -8
Without using width parameter :  -1000
Using width parameter :  11000


numpy.packbits(myarray, axis=None) : 

This function is used to packs the elements of a binary-valued array into bits in a uint8 array.The result is padded to full bytes by inserting zero bits at the end.

In [15]:
import numpy as np
 
# creating an array using 
# array function
a = np.array([[[1,0,1],
             [0,1,0]],
             [[1,1,0],
             [0,0,1]]])
 
# packing elements of an array
# using packbits() function
b = np.packbits(a, axis=-1)
 
print(b)

[[[160]
  [ 64]]

 [[192]
  [ 32]]]


In [16]:
import numpy as np
 
# creating an array using 
# array function
a = np.array([[2], [7], [23]], dtype=np.uint8)
 
# packing elements of an array
# using packbits() function
b = np.unpackbits(a, axis = 1)
 
print(b)

[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 1 0 1 1 1]]


Mathematical Function :

numpy.sin(x[, out]) = ufunc ‘sin’) :

This mathematical function helps user to calculate trignmetric sine for all x(being the array elements)

In [17]:
import numpy as np
import math
 
in_array = [0, math.pi / 2, np.pi / 3, np.pi]
print ("Input array : \n", in_array)
 
Sin_Values = np.sin(in_array)
print ("\nSine values : \n", Sin_Values)

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

Sine values : 
 [0.00000000e+00 1.00000000e+00 8.66025404e-01 1.22464680e-16]


numpy.cos(x[, out]) = ufunc ‘cos’) :

This mathematical function helps user to calculate trignmetric cosine for all x(being the array elements).

In [18]:
import numpy as np
import math
 
in_array = [0, math.pi / 2, np.pi / 3, np.pi]
print ("Input array : \n", in_array)
 
cos_Values = np.cos(in_array)
print ("\nCosine values : \n", cos_Values)

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

Cosine values : 
 [ 1.000000e+00  6.123234e-17  5.000000e-01 -1.000000e+00]


numpy.sinh(x[, out]) = ufunc ‘sin’) : 

This mathematical function helps user to calculate hyperbolic sine for all x(being the array elements

In [19]:
import numpy as np
import math
 
in_array = [0, math.pi / 2, np.pi / 3, np.pi]
print ("Input array : \n", in_array)
 
Sinh_Values = np.sinh(in_array)
print ("\nSine Hyperbolic values : \n", Sinh_Values)

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

Sine Hyperbolic values : 
 [ 0.          2.3012989   1.24936705 11.54873936]


 
numpy.cosh(x[, out]) = ufunc ‘cos’) : 

This mathematical function helps user to calculate hyperbolic cosine for all x(being the array elements)

In [20]:
import numpy as np
import math
 
in_array = [0, math.pi / 2, np.pi / 3, np.pi]
print ("Input array : \n", in_array)
 
cosh_Values = np.cosh(in_array)
print ("\ncosine Hyperbolic values : \n", cosh_Values)

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

cosine Hyperbolic values : 
 [ 1.          2.50917848  1.60028686 11.59195328]


numpy.around(arr, decimals = 0, out = None) : 

This mathematical function helps user to evenly round array elements to the given number of decimals.

In [21]:
import numpy as np
 
in_array = [.5, 1.5, 2.5, 3.5, 4.5, 10.1]
print ("Input array : \n", in_array)
 
round_off_values = np.around(in_array)
print ("\nRounded values : \n", round_off_values)
 
 
in_array = [.53, 1.54, .71]
print ("\nInput array : \n", in_array)
 
round_off_values = np.around(in_array)
print ("\nRounded values : \n", round_off_values)
 
in_array = [.5538, 1.33354, .71445]
print ("\nInput array : \n", in_array)
 
round_off_values = np.around(in_array, decimals = 3)
print ("\nRounded values : \n", round_off_values)

Input array : 
 [0.5, 1.5, 2.5, 3.5, 4.5, 10.1]

Rounded values : 
 [ 0.  2.  2.  4.  4. 10.]

Input array : 
 [0.53, 1.54, 0.71]

Rounded values : 
 [1. 2. 1.]

Input array : 
 [0.5538, 1.33354, 0.71445]

Rounded values : 
 [0.554 1.334 0.714]


numpy.round_(arr, decimals = 0, out = None) :

This mathematical function round an array to the given number of decimals 

In [22]:
import numpy as np
 
in_array = [.5, 1.5, 2.5, 3.5, 4.5, 10.1]
print ("Input array : \n", in_array)
 
round_off_values = np.round_(in_array)
print ("\nRounded values : \n", round_off_values)
 
 
in_array = [.53, 1.54, .71]
print ("\nInput array : \n", in_array)
 
round_off_values = np.round_(in_array)
print ("\nRounded values : \n", round_off_values)
 
in_array = [.5538, 1.33354, .71445]
print ("\nInput array : \n", in_array)
 
round_off_values = np.round_(in_array, decimals = 3)
print ("\nRounded values : \n", round_off_values)

Input array : 
 [0.5, 1.5, 2.5, 3.5, 4.5, 10.1]

Rounded values : 
 [ 0.  2.  2.  4.  4. 10.]

Input array : 
 [0.53, 1.54, 0.71]

Rounded values : 
 [1. 2. 1.]

Input array : 
 [0.5538, 1.33354, 0.71445]

Rounded values : 
 [0.554 1.334 0.714]


numpy.exp(array, out = None, where = True, casting = ‘same_kind’, order = ‘K’, dtype = None) : 

This mathematical function helps user to calculate exponential of all the elements in the input array

In [23]:
import numpy as np
 
in_array = [1, 3, 5]
print ("Input array : ", in_array)
 
out_array = np.exp(in_array)
print ("Output array : ", out_array)

Input array :  [1, 3, 5]
Output array :  [  2.71828183  20.08553692 148.4131591 ]



numpy.log(x[, out] = ufunc ‘log1p’) :

This mathematical function helps user to calculate Natural logarithm of x where x belongs to all the input array elements

In [24]:
import numpy as np
 
in_array = [1, 3, 5, 2**8]
print ("Input array : ", in_array)
 
out_array = np.log(in_array)
print ("Output array : ", out_array)
 
 
print("\nnp.log(4**4) : ", np.log(4**4))
print("np.log(2**8) : ", np.log(2**8))

Input array :  [1, 3, 5, 256]
Output array :  [0.         1.09861229 1.60943791 5.54517744]

np.log(4**4) :  5.545177444479562
np.log(2**8) :  5.545177444479562


numpy.reciprocal(x, /, out=None, *, where=True) : 

This mathematical function is used to calculate reciprocal of all the elements in the input array.

In [25]:
import numpy as np
 
in_num = 2.0
print ("Input  number : ", in_num)
 
out_num = np.reciprocal(in_num)
print ("Output number : ", out_num)

Input  number :  2.0
Output number :  0.5


In [26]:
# Python program explaining
# divide() function
import numpy as np
 
# input_array
arr1 = [2, 27, 2, 21, 23]
arr2 = [2, 3, 4, 5, 6]
print ("arr1         : ", arr1)
print ("arr2         : ", arr2)
 
# output_array
out = np.divide(arr1, arr2)
print ("\nOutput array : \n", out)

arr1         :  [2, 27, 2, 21, 23]
arr2         :  [2, 3, 4, 5, 6]

Output array : 
 [1.         9.         0.5        4.2        3.83333333]


Complex number Function :

numpy.isreal(array) : 
Test element-wise whether it is a real number or not(not infinity or not Not a Number) and return the result as a boolean array.

In [27]:
import numpy as geek 
 
print("Is Real : ", geek.isreal([1+1j, 0j]), "\n")
 
print("Is Real : ", geek.isreal([1, 0]), "\n")

Is Real :  [False  True] 

Is Real :  [ True  True] 



In [28]:
#importing numpy
import numpy as np
 
in_complx1 = 2+4j
out_complx1 = np.conj(in_complx1)
print ("Output conjugated complex number of  2+4j : ", out_complx1)
 
in_complx2 =5-8j
out_complx2 = np.conj(in_complx2)
print ("Output conjugated complex number of 5-8j: ", out_complx2)

Output conjugated complex number of  2+4j :  (2-4j)
Output conjugated complex number of 5-8j:  (5+8j)


Special functions :

numpy.cbrt(arr, out = None, ufunc ‘cbrt’) : This mathematical function helps user to calculate cube root of x for all x being the array elements.

In [29]:
import numpy as np
  
arr1 = [1, 27000, 64, -1000]
print ("cbrt Value of arr1 : \n", np.cbrt(arr1))
  
arr2 = [1024 ,-128]
print ("\ncbrt Value of arr2 : ", np.cbrt(arr2))

cbrt Value of arr1 : 
 [  1.  30.   4. -10.]

cbrt Value of arr2 :  [10.0793684 -5.0396842]


In [30]:
# importing the numpy
import numpy as np
 
in_array = [1, 2, 3, 4, 5, 6, 7, 8 ]
print ("Input array : ", in_array)
 
out_array = np.clip(in_array, a_min = 2, a_max = 6)
print ("Output array : ", out_array)

Input array :  [1, 2, 3, 4, 5, 6, 7, 8]
Output array :  [2 2 3 4 5 6 6 6]


String Operations :

numpy.lower() : 

This function returns the lowercase string from the given string. It converts all uppercase characters to lowercase. If no uppercase characters exist, it returns the original string

In [31]:
import numpy as np
 
# converting to lowercase
print(np.char.lower(['GEEKS', 'FOR']))
 
# converting to lowercase
print(np.char.lower('GEEKS'))

['geeks' 'for']
geeks


numpy.split() :

This function returns a list of strings after breaking the given string by the specified separator.

In [32]:
import numpy as np
 
# splitting a string
print(np.char.split('geeks for geeks'))
 
# splitting a string
print(np.char.split('geeks, for, geeks', sep = ','))

['geeks', 'for', 'geeks']
['geeks', ' for', ' geeks']


numpy.join() : 

This function is a string method and returns a string in which the elements of sequence have been joined by str separator

In [33]:
import numpy as np
 
# splitting a string
print(np.char.join('-', 'geeks'))
 
# splitting a string
print(np.char.join(['-', ':'], ['geeks', 'for']))

g-e-e-k-s
['g-e-e-k-s' 'f:o:r']


String Information :
numpy.count() : This function returns the number of occurrences of a substring in the given string

In [34]:
import numpy as np
 
a=np.array(['geeks', 'for', 'geeks'])
 
# counting a substring
print(np.char.count(a,'geek'))
 
# counting a substring
print(np.char.count(a, 'fo'))

[1 0 1]
[0 1 0]


numpy.rfind() : 

This function returns the highest index of the substring if found in given string. If not found then it returns -1.

In [35]:
import numpy as np
 
a=np.array(['geeks', 'for', 'geeks'])
 
# counting a substring
print(np.char.rfind(a,'geek'))
 
# counting a substring
print(np.char.rfind(a, 'fo'))

[ 0 -1  0]
[-1  0 -1]


numpy.isnumeric() : 

This function returns “True” if all characters in the string are numeric characters, Otherwise, It returns “False”.

In [36]:
import numpy as np
 
 
# counting a substring
print(np.char.isnumeric('geeks'))
 
# counting a substring
print(np.char.isnumeric('12geeks'))

False
False


String Comparison :

numpy.equal(): This function checks for string1 == string2 elementwise.

 
numpy.not_equal(): This function checks whether two string is unequal or not.

In [42]:
import numpy as np
 
# comparing a string elementwise
# using not_equal() method
a = np.char.not_equal('geeks', 'for')
 
print(a)


True



numpy.greater(): This function checks whether string1 is greater than string2 or not.

In [43]:
import numpy as np
 
# comparing a string elementwise
# using greater() method
a=np.char.greater('geeks','for')
 
print(a)

True
