Reshape NumPy Array :

In [1]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))

# length of array
n = array.size

# N-D array N dimension
N = 4

# calculating M
M = n//N

# reshaping numpy array
# converting it to 2-D from 1-D array
reshaped1 = array.reshape((N, M))

# printing reshaped array
print("First Reshaped Array : ")
print(reshaped1)

# creating another reshaped array
reshaped2 = np.reshape(array, (2, 8))

# printing reshaped array
print("Second Reshaped Array : ")
print(reshaped2)


Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second Reshaped Array : 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [2]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))


# reshaping numpy array
# converting it to 3-D from 1-D array
reshaped = array.reshape((2, 2, 4))

# printing reshaped array
print("Reshaped 3-D Array : ")
print(reshaped)


Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Reshaped 3-D Array : 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [3]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([[1, 2, 3],
				[4, 5, 6],
				[7, 8, 9]])

# printing array
print(" 2-D Array : ")
print(array)


# reshaping numpy array
# converting it to 1-D from 2-D array
reshaped = array.reshape((9))

# or we can use unknown dimension
# reshaped = array.reshape((-1))

# printing reshaped array
print("Reshaped 1-D Array : ")
print(reshaped)


 2-D Array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped 1-D Array : 
[1 2 3 4 5 6 7 8 9]


In [4]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))


# reshaping numpy array
# converting it to 3-D from 1-D array
reshaped1 = array.reshape((2, 2, -1))

# printing reshaped array
print("First Reshaped Array : ")
print(reshaped1)


# converting it to 2-D array
reshaped2 = array.reshape((4, -1))

# printing reshaped array
print("Second Reshaped Array : ")
print(reshaped2)


Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array : 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
Second Reshaped Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


 Numpy matrix.resize() :

In [12]:
# import the important module in python 
import numpy as np 
		
# make matrix with numpy 
gfg = np.matrix('[64, 1; 12, 3]') 
		
# applying matrix.resize() method 
gfg.resize((1, 4)) 
	
print(gfg) 


[[64  1 12  3]]


In [14]:
# import the important module in python 
import numpy as np 
		
# make a matrix with numpy 
g = np.matrix('[1, 2; 4, 5; 7, 8]') 
		
# applying matrix.resize() method 
g.resize((2, 3)) 
	
print(g) 


[[1 2 4]
 [5 7 8]]


Numpy matrix.reshape() :

In [15]:
# import the important module in python 
import numpy as np 
		
# make matrix with numpy 
gfg = np.matrix('[64, 1; 12, 3]') 
		
# applying matrix.reshape() method 
geeks = gfg.reshape((1, 4)) 
	
print(geeks) 


[[64  1 12  3]]


In [16]:
# import the important module in python 
import numpy as np 
		
# make a matrix with numpy 
gfg = np.matrix('[1, 2; 4, 5; 7, 8]') 
		
# applying matrix.reshape() method 
geeks = gfg.reshape((2, 3)) 
	
print(geeks) 


[[1 2 4]
 [5 7 8]]


NumPy Array Shape :

In [17]:
import numpy as npy

# creating a 2-d array
arr1 = npy.array([[1, 3, 5, 7], [2, 4, 6, 8]])

# creating a 3-d array
arr2 = npy.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr1.shape)
print(arr2.shape)


(2, 4)
(2, 2, 2)


In [18]:
import numpy as npy

# creating an array of 6 dimension
# using ndim
arr = npy.array([2, 4, 6, 8, 10], ndmin=6)

# printing array
print(arr)

# verifying the value of last dimension
# as 5
print('shape of an array :', arr.shape)


[[[[[[ 2  4  6  8 10]]]]]]
shape of an array : (1, 1, 1, 1, 1, 5)


In [19]:
import numpy as np

# Create an array of tuples
array_of_tuples = np.array([(1, 2), (3, 4), (5, 6), (7, 8)])

# Display the array
print("Array of Tuples:")
print(array_of_tuples)

# Determine and display the shape
shape = array_of_tuples.shape
print("\nShape of Array:", shape)


Array of Tuples:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Shape of Array: (4, 2)


Change the dimension of a NumPy array :

In [20]:
# importing numpy
import numpy as np


def main():

	# initialising array
	print('Initialised array')
	gfg = np.array([1, 2, 3, 4])
	print(gfg)

	# checking current shape
	print('current shape of the array')
	print(gfg.shape)
	
	# modifying array according to new dimensions
	print('changing shape to 2,2')
	gfg.shape = (2, 2)
	print(gfg)

if __name__ == "__main__":
	main()


Initialised array
[1 2 3 4]
current shape of the array
(4,)
changing shape to 2,2
[[1 2]
 [3 4]]


In [21]:
# importing numpy
import numpy as np


def main():

	# initialising array
	gfg = np.arange(1, 10)
	print('initialised array')
	print(gfg)
	
	# reshaping array into a 3x3 with order C
	print('3x3 order C array')
	print(np.reshape(gfg, (3, 3), order='C'))

	# reshaping array into a 3x3 with order F
	print('3x3 order F array')
	print(np.reshape(gfg, (3, 3), order='F'))

	# reshaping array into a 3x3 with order A
	print('3x3 order A array')
	print(np.reshape(gfg, (3, 3), order='A'))


if __name__ == "__main__":
	main()


initialised array
[1 2 3 4 5 6 7 8 9]
3x3 order C array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3x3 order F array
[[1 4 7]
 [2 5 8]
 [3 6 9]]
3x3 order A array
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
# importing numpy
import numpy as np


def main():

	# initialise array
	gfg = np.arange(1, 10)
	print('initialised array')
	print(gfg)
	
	# resized array with dimensions in
	# range of original array
	gfg1=np.resize(gfg, (3, 3))
	print('3x3 array')
	print(gfg1)
	
	# resized array with dimensions larger than
	# original array
	gfg2=np.resize(gfg, (4, 4))
	
	# extra spaces will be filled with repeated
	# copies of original array
	print('4x4 array')
	print(gfg2)
	
	# resize array with dimensions larger than 
	# original array
	gfg.resize(5, 5)
	
	# extra spaces will be filled with zeros
	print('5x5 array')
	print(gfg)


if __name__ == "__main__":
	main()


initialised array
[1 2 3 4 5 6 7 8 9]
3x3 array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
4x4 array
[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]
 [4 5 6 7]]
5x5 array
[[1 2 3 4 5]
 [6 7 8 9 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


numpy.ndarray.resize() function :

In [23]:
# Python program explaining 
# numpy.ndarray.resize() function 
		
# importing numpy as geek 
import numpy as geek 
	
arr = geek.array([[0, 1], [2, 3]]) 

# this function change the shape and size 
# of the array & return None 
gfg = arr.resize((2, 1)) 

print (gfg) 


None


In [24]:
# Python program explaining 
# numpy.ndarray.resize() function 
		
# importing numpy as geek 
import numpy as geek 
	
arr = geek.array([[0, 1], [2, 3]], order = 'F') 

# this function change the shape and size 
# of the array & return None 
gfg = arr.resize((2, 1)) 

print (gfg) 


None


Flatten a Matrix in Python using NumPy :

In [25]:
# importing numpy as np 
import numpy as np 

# declare matrix with np 
gfg = np.array([[2, 3], [4, 5]]) 

# using array.flatten() method 
flat_gfg = gfg.flatten() 
print(flat_gfg) 


[2 3 4 5]


In [26]:
# importing numpy as np 
import numpy as np 

# declare matrix with np 
gfg = np.array([[6, 9], [8, 5], [18, 21]]) 

# using array.flatten() method 
gfg.flatten() 


array([ 6,  9,  8,  5, 18, 21])

In [27]:
# importing numpy as np 
import numpy as np 

# declare matrix with np 
gfg = np.array([[6, 9, 12], [8, 5, 2], [18, 21, 24]]) 

# using array.flatten() method 
flat_gfg = gfg.flatten(order='A') 
print(flat_gfg) 


[ 6  9 12  8  5  2 18 21 24]


numpy.moveaxis() function :

In [28]:
# Python program explaining 
# numpy.moveaxis() function 

# importing numpy as geek 
import numpy as geek 

arr = geek.zeros((1, 2, 3, 4)) 

gfg = geek.moveaxis(arr, 0, -1).shape 

print (gfg) 


(2, 3, 4, 1)


In [29]:
# Python program explaining 
# numpy.moveaxis() function 

# importing numpy as geek 
import numpy as geek 

arr = geek.zeros((1, 2, 3, 4)) 

gfg = geek.moveaxis(arr, -1, 0).shape 

print (gfg) 


(4, 1, 2, 3)


numpy.swapaxes() function :

In [30]:
# Python program explaining 
# numpy.swapaxes() function 

# importing numpy as geek 
import numpy as geek 

arr = geek.array([[2, 4, 6]]) 

gfg = geek.swapaxes(arr, 0, 1) 

print (gfg) 


[[2]
 [4]
 [6]]


In [31]:
# Python program explaining 
# numpy.swapaxes() function 

# importing numpy as geek 
import numpy as geek 

arr = geek.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]]) 

gfg = geek.swapaxes(arr, 0, 2) 

print (gfg) 


[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


Numpy matrix.swapaxes() :

In [32]:
# import the important module in python 
import numpy as np 
			
# make matrix with numpy 
gfg = np.matrix('[4, 1; 12, 3]') 
			
# applying matrix.swapaxes() method 
geek = gfg.swapaxes(0, 1) 

print(geek) 


[[ 4 12]
 [ 1  3]]


In [33]:
# import the important module in python 
import numpy as np 
			
# make matrix with numpy 
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]') 
			
# applying matrix.swapaxes() method 
geek = gfg.swapaxes(1, 1) 

print(geek) 


[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]


numpy.vsplit() function :

In [34]:
# Python program explaining 
# numpy.vsplit() function 

# importing numpy as geek 
import numpy as geek 

arr = geek.arange(9.0).reshape(3, 3) 

gfg = geek.vsplit(arr, 1) 

print (gfg) 


[array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])]


In [35]:
# Python program explaining 
# numpy.vsplit() function 

# importing numpy as geek 
import numpy as geek 

arr = geek.arange(36.0).reshape(6, 6) 

gfg = geek.vsplit(arr, 2) 

print (gfg) 


[array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.]]), array([[18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.]])]


numpy.hsplit() function :

In [36]:
# Python program explaining 
# numpy.hsplit() function 

# importing numpy as geek 
import numpy as geek 

arr = geek.arange(16.0).reshape(4, 4) 

gfg = geek.hsplit(arr, 2) 

print (gfg) 


[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


In [37]:
# Python program explaining 
# numpy.hsplit() function 

# importing numpy as geek 
import numpy as geek 

arr = geek.arange(27.0).reshape(3, 3, 3) 

gfg = geek.hsplit(arr, 1) 

print (gfg) 


[array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]]])]


Numpy MaskedArray.reshape() function  :

In [38]:
# Python program explaining 
# numpy.MaskedArray.reshape() method 
	
# importing numpy as geek 
# and numpy.ma module as ma 
import numpy as geek 
import numpy.ma as ma 
	
# creating input array 
in_arr = geek.array([1, 2, 3, -1]) 
print ("Input array : ", in_arr) 
	
# Now we are creating a masked array. 
# by making third entry as invalid. 
mask_arr = ma.masked_array(in_arr, mask =[1, 0, 1, 0]) 
print ("Masked array : ", mask_arr) 
	
# applying MaskedArray.reshape methods to make 
# it a 2d masked array 
out_arr = mask_arr.reshape(2, 2) 
print ("Output 2D masked array : ", out_arr) 


Input array :  [ 1  2  3 -1]
Masked array :  [-- 2 -- -1]
Output 2D masked array :  [[-- 2]
 [-- -1]]


In [39]:
# Python program explaining 
# numpy.MaskedArray.reshape() method 
	
# importing numpy as geek 
# and numpy.ma module as ma 
import numpy as geek 
import numpy.ma as ma 
	
# creating input array 
in_arr = geek.array([[[ 2e8, 3e-5]], [[ -45.0, 2e5]]]) 
print ("Input array : ", in_arr) 
	
# Now we are creating a masked array. 
# by making one entry as invalid. 
mask_arr = ma.masked_array(in_arr, mask =[[[ 1, 0]], [[ 0, 0]]]) 
print ("3D Masked array : ", mask_arr) 
	
# applying MaskedArray.reshape methods to make 
# it a 2d masked array 
out_arr = mask_arr.reshape(1, 4) 
print ("Output 2D masked array : ", out_arr) 
print() 

# applying MaskedArray.reshape methods to make 
# it a 1d masked array 
out_arr = mask_arr.reshape(4, ) 
print ("Output 1D masked array : ", out_arr) 


Input array :  [[[ 2.0e+08  3.0e-05]]

 [[-4.5e+01  2.0e+05]]]
3D Masked array :  [[[-- 3e-05]]

 [[-45.0 200000.0]]]
Output 2D masked array :  [[-- 3e-05 -45.0 200000.0]]

Output 1D masked array :  [-- 3e-05 -45.0 200000.0]


Numpy matrix.squeeze() :

In [40]:
# import the important module in python 
import numpy as np 
			
# make matrix with numpy 
gfg = np.matrix('[[4], [12]]') 
			
# applying matrix.squeeze() method 
gfg.squeeze() 

print(gfg) 


[[ 4 12]]


In [41]:
# import the important module in python 
import numpy as np 
			
# make matrix with numpy 
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]') 
			
# applying matrix.squeeze() method 
gfg.squeeze() 

print(gfg) 


[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
